<?php
// $Id$

/**
 * @file
 * @todo
 */

/**
 * Implementation of hook_menu().
 */
function sitestate_menu() {
  $items = array();

  $items['admin/settings/sitestate'] = array(
    'title' => 'Site states',
    'page callback' => 'sitestate_admin_page',
    'access arguments' => array('administer site state'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'sitestate.admin.inc',
  );
  $items['admin/settings/sitestate/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/settings/sitestate/add'] = array(
    'title' => 'Add site state',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sitestate_edit_state'),
    'access arguments' => array('administer site state'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'sitestate.admin.inc',
  );
  $items['admin/settings/sitestate/%sitestate/edit'] = array(
    'title' => 'Edit site state',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sitestate_edit_state', 3),
    'access arguments' => array('administer site state'),
    'type' => MENU_CALLBACK,
    'file' => 'sitestate.admin.inc',
  );
  $items['admin/settings/sitestate/%sitestate/delete'] = array(
    'title' => 'Delete site state',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sitestate_delete_state', 3),
    'access arguments' => array('administer site state'),
    'type' => MENU_CALLBACK,
    'file' => 'sitestate.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function sitestate_perm() {
  return array('administer site state', 'apply site state');
}

function sitestate_form_system_site_maintenance_settings_alter(&$form, &$form_state) {
  $options = array();
  $states = sitestate_load_all();
  foreach ($states as $state) {
    $options[$state->ssid] = $state->title;
  }
  $form['sitestate_selected_state'] = array(
    '#type' => 'radios',
    '#title' => t('Site state'),
    '#default_value' => variable_get('sitestate_selected_state', 1),
    '#options' => $options  ,
    '#weight' => -10,
    '#description' => t('TODO what does this do.'),
  );
  if ($differences = sitestate_get_state_overrides()) {
    $form['warning'] = array(
      '#value' => t('TODO This message appears if the selected state does not match the current state.'),
    );
    print_r($differences);
  }
  
  $form['override'] = array(
    '#type' => 'fieldset',
    '#title' => t('Override'),
    '#weight' => -9,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['override']['site_offline'] = $form['site_offline'];
  unset($form['site_offline']);
  unset($form['site_offline_message']);
dpm($form);
}

/**
 * Load single sites state.
 *
 * @todo
 */
function sitestate_load($ssid) {
  $sitestate = array();
  if (!isset($sitestate[$ssid])) {
    $result = db_query('SELECT * FROM {sitestate} WHERE ssid = %d', $ssid);
    $sitestate = db_fetch_object($result);
  }
  return $sitestate;
}

/**
 * Load all sites states.
 *
 * @param $ssids
 *   Array of site state ids.
 * @return array of site state objects.
 */
function sitestate_load_all() {
  static $sitestates = array();
  if (empty($sitestates)) {
    $result = db_query('SELECT * FROM {sitestate}');
    while ($sitestate = db_fetch_object($result)) {
      $sitestates[$sitestate->ssid] = $sitestate;
    }
  }
  return $sitestates;
}

/**
 * Load single sites state including state settings.
 *
 * @param $ssid
 *   Site state id.
 * @return site state object including state's settings objects.
 */
function sitestate_get_sitestate($ssid) {
  $sitestate = sitestate_load($ssid);
  $sitestate->settings = sitestate_settings_load($ssid);
  return $sitestate;
}

/**
 * Load setting of a site state.
 *
 * @param $ssid
 *   Site state id.
 * @return array of site state settings objects.
 */
function sitestate_settings_load($ssid) {
  static $settings = array();
  if (!$settings) {
    $result = db_query('SELECT * FROM {sitestate_settings} WHERE ssid = %d', $ssid);
    while ($setting = db_fetch_object($result)) {
      $settings[$setting->type .':'. $setting->name] = $setting;
    }
  }
  return $settings;
}

/**
 * Check if the current state maches the last selected state.
 *
 * @return found differences
 *   Array of found differences
 *   FALSE if no difference are found.
 */
//@todo In what file to place this function
function sitestate_check_state() {
  $differences = array();
  
  $selected_state = sitestate_settings_load(variable_get('sitestate_selected_state', 1));
  $current_state = sitestate_get_current_state(array_keys($selected_state));
  foreach ($selected_state as $key => $selected) {
    if (isset($current_state[$key])) {
      if ($selected == $current_state[$key]) {
        list($type, $name) = explode($key);
        $differences[] = array(
          'type' => $type,
          'name' => $name,
          'value' => $current_state[$key],
        );
      }
    }
    else {
      $differences[] = array(
        'type' => $type,
        'name' => $name,
        'value' => t('Undefined'),
      );
    }
  }
  return empty($differences) ? FALSE : $differences;
}

/**
 * Return the current state of specified type-name pairs
 *
 * @todo
 */
//@todo In what file to place this function
function sitestate_get_current_state($keys) {
  global $conf;
  $current_state = array();

  foreach ($keys as $key) {
    list($type, $name) = explode($key);
    switch ($type) {
      case 'module':
        $current_state[$key] = module_exists($name);
        break;
      case 'variable':
        // We don't use the variable_get() here to avoid the variable_get default.
        if (isset($conf[$name])) {
          $current_state[$key] = $conf[$name];
        }
        break;
    }
  }
  return $current_state;
}