<?php
// $Id$

/**
 * @file
 * @todo
 */

/**
 * @todo
 */
function sitestate_admin_state(&$form_state, $sitestate) {
  $form['temp'] = array('#value' => '... administer site states here ...');
  return $form;
}

/**
 * @todo
 */
function sitestate_edit_state($sitestate) {
  $form['temp'] = array('#value' => '... edit site states here ...');
  return $form;
}

/**
 * @todo
 */
function sitestate_delete_state($sitestate) {
  $form['temp'] = array('#value' => '... confirm delete site states here ...');
  return $form;
}
